### ISSUE TITLE
Error on installing to PS 1.6.1.1

### ISSUE THREAD

**Issue by babyewok** [firstred/mpsendtoafriend#2]
When I try and install to PS 1.6.1.1, I get this error:

[PrestaShop] Fatal error in module file :C:\UniServerZ\www\KD_shop\modules\mpsendtoafriend\mpsendtoafriend.php:
require_once(): Failed opening required 'C:\UniServerZ\www\KD_shop/modules/mpsendtoafriend/vendor/autoload.php' (include_path='C:\UniServerZ\www\KD_shop\tools\htmlpurifier/standalone;.;C:/UniServerZ/home/us_pear/PEAR')

**Comment by firstred** [comment]
use composer!
